# Generated by Django 4.1.11 on 2023-09-05 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sessions", "0001_initial"),
        ("shopping_cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sessions.session",
            ),
        ),
    ]
